[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = []

[start]
cmd = "node telegram-bot.js"

# Указываем, что это Node.js проект
[providers]
nodejs = true

